### ISSUE TITLE
ISSUE: 0.246.00 RF1 Configurator

### ISSUE THREAD

**Issue by chargerdude70** [RaceFlightOne/RaceFlightOne#102]
Win64 Setup >> 4. Update ESC: After step 1 is complete and click "Next", it bootloops back to step 1.

**Comment by Arti3DPlayer** [comment]
@chargerdude70 `Remove your props !!!` should be your first step, then when you click next what happen ?(it should show you window with loading progress)

**Comment by chargerdude70** [comment]
This credit card comes up. 
![please wait](https://cloud.githubusercontent.com/assets/6600288/25660385/f791cc3a-2fd9-11e7-8815-4a4fe65610e7.PNG)

After it closes it reverts back to this. 

![next](https://cloud.githubusercontent.com/assets/6600288/25660443/31545794-2fda-11e7-8b42-1ea45d86a423.PNG)

It never moves onto next step. Just loops to first step. There is no "Finish" or "Done" option

**Comment by Arti3DPlayer** [comment]
@chargerdude70 I tested on windows x64 it works for me. I will try to ask someone to test too

**Comment by rs2k** [comment]
I'm closing this issue. Please reopen if it's still happening. :)
