### ISSUE TITLE
Suggestion: 0.246.00/0.246.083 Filtering 

### ISSUE THREAD

**Issue by chargerdude70** [RaceFlightOne/RaceFlightOne#103]
Quick Change filter levels: Shouldn't the "Normal" filter levels be same as the "default, as flashed"? If not, add a "Default" option. The way it is, there is no "choice" in the drop down to get back to stock. 

![as flashed](https://cloud.githubusercontent.com/assets/6600288/25658470/f73b79e2-2fd0-11e7-9b16-45016ca7211d.PNG)

![normal](https://cloud.githubusercontent.com/assets/6600288/25658469/f739e5dc-2fd0-11e7-9c5a-a412662388cf.PNG)

**Comment by rs2k** [comment]
This has been resolved. :)
