### ISSUE TITLE
Issue: RC Smoothing slider in Configurator tab

### ISSUE THREAD

**Issue by chargerdude70** [RaceFlightOne/RaceFlightOne#105]
100% RC Smoothing in the slider tab when saved does not export a full value of 4.0 into CLI. Release notes state value range is from .1 to 4.0 yet when slider is set to 100% and saved, a CLI Dump shows a value of 3.0. If I put a value of 4.0 in CLI, the slider shows a value of 133.333.  Shouldn't either the full value of RC Smoothing be set in CLI if 100% is place in the slider value or the slider be capable of going to 133.333?
![rc smoothing](https://cloud.githubusercontent.com/assets/6600288/25670135/b4bcb81e-2ff9-11e7-9389-9e238a7d4c7f.PNG)

**Comment by PGIII** [comment]
fixed in latest gui
