### ISSUE TITLE
256 - Copy profiles to each other

### ISSUE THREAD

**Issue by Therotak** [RaceFlightOne/RaceFlightOne#109]
Hey there,

it would be extremly helpful to be able to lets say copy profile 1 to slot 2. So you are able to adjust it and test it without doing everything by hand.

thanks!

**Comment by Arti3DPlayer** [comment]
@Therotak As for me a lot of buttons make program interface hard for new users. Maybe when user will be able create unlimited own profiles, then this copy function is needed

**Comment by rs2k** [comment]
release 1.0 milestone

**Comment by ankjaers** [comment]
Could be hidden from the primary interface by making it available with a right click

**Comment by Arti3DPlayer** [comment]
Available in 0.314.1
