### ISSUE TITLE
LED light mode selection and color control

### ISSUE THREAD

**Issue by Flyngbeary** [RaceFlightOne/RaceFlightOne#110]
RF1 configurator appears that it will let you select different light modes, but when LED switch is enabled you can only cycle thru the available modes regardless of mode selected each time you want to turn on or off LED lights.  Tried to assign switch to control color but does not seem to work.

**Comment by rs2k** [comment]
Set to release 1.0 milestone

**Comment by PGIII** [comment]
fixed in 420
