### ISSUE TITLE
Configurator: People seem to miss the "make sure the battery is disconnected" in motor wiz

### ISSUE THREAD

**Issue by hjns** [RaceFlightOne/RaceFlightOne#114]
A lot of people seem to miss the "make sure the battery is disconnected" in motor wiz and get the "Make sure your drone is immovable" error.  I suggest making the DISCONNECTED larger and more prominent and  adding something like "This is also caused by the battery not being disconnected in the previous screen" to the "Make sure your drone is immovable" error popup.

**Comment by Arti3DPlayer** [comment]
could you give a screenshot please

**Comment by hjns** [comment]
![selection_348](https://cloud.githubusercontent.com/assets/1418353/26506908/1cc7fa16-421c-11e7-9fb1-ff66bc4fac25.png)
![selection_347](https://cloud.githubusercontent.com/assets/1418353/26506907/1cc3d0ee-421c-11e7-8221-ec0173e53b48.png)

**Comment by rs2k** [comment]
![image](https://cloud.githubusercontent.com/assets/9113146/26810052/27245b26-4a37-11e7-97b4-1aa0d6b0f167.png)

This should be change to "Please make sure your battery is DISCONNECTED and your quad is completely still."

**Comment by Arti3DPlayer** [comment]
fixed
