### ISSUE TITLE
RC rate over 2 with betaflight rates doesn't work. makes quad crazy

### ISSUE THREAD

**Issue by blazomusic** [RaceFlightOne/RaceFlightOne#115]
Calculator shows more than million degrees. But it's not only calculator bug. Quad gets crazy when any input is given. 
It starts over 2 RC rate. (when using betaflight rates)
For people who doesn't use super rates, its not possible to go over 400deg/s now.
2 rc rate is 400deg/s

**Comment by Arti3DPlayer** [comment]
@blazomusic provide screenshot please

**Comment by blazomusic** [comment]
![image](https://cloud.githubusercontent.com/assets/21251172/26592480/2697f62a-4561-11e7-91a3-3a6dab71d238.png)

**Comment by rs2k** [comment]
Should be fixed in 271. Closing issue for now. :)
