### ISSUE TITLE
Enhancement: Save PID/FILTER values in Blackbox log

### ISSUE THREAD

**Issue by denovich** [RaceFlightOne/RaceFlightOne#119]
I pull a ton of log files while tuning.  Remembering what changed between log files is very difficult, and without taking detailed notes, my log files are quickly rendered pointless.

Also sharing log files is less useful without knowing what the initial settings were.

Recent BF blackbox logs include all this setting data, which is viewable directly within the BFBlackbox Explorer.  Super handy.

**Comment by PGIII** [comment]
dump is now encluded in the log
