### ISSUE TITLE
Enhancement: add 'diff' function to console so user can see/preserve changes to defaults

### ISSUE THREAD

**Issue by denovich** [RaceFlightOne/RaceFlightOne#120]
How it should work:

I type 'diff' in the console
the console dumps a list of settings that are different than defaults.

I can then save this dump, and more easily apply only those relevant settings to a new build.

This is very helpful bit of functionality in the BF configurator.  
It makes updating to new firmware builds much easier.

**Comment by Arti3DPlayer** [comment]
@denovich on PID tuning tab you can select default values and compare. Just don't hit save button

**Comment by proggod** [comment]
We plan to have a better way for upgrading by the time we get to v1, so going to close out this issue in the mean time
