### ISSUE TITLE
LUA Script - Main Splash Page  

### ISSUE THREAD

**Issue by carloscampos775** [RaceFlightOne/RaceFlightOne#121]
Main splash page not working correctly. The display will not fully display “Place both sticks in the bottom center to enable program mode”. However, after entering programming mode the VTX, PIDs, & other menus will work as normal. After saving and exiting, the main page goes back to the display issue.

**Comment by MilanFPV** [comment]
I have it, too

**Comment by PGIII** [comment]
will be fixed with new lua
