### ISSUE TITLE
295 only arms first time

### ISSUE THREAD

**Issue by gizmatron** [RaceFlightOne/RaceFlightOne#123]
295 multishot sbus plug in lipo double arms fine motors spin.. disarm and it wont rearm.. just a single beep everytime you flick arm switch

**Comment by TheSkyFox** [comment]
Same here 295 Oneshot sbus, arms fine the first time. disarm and it won't rearm.  Also the Telemetry screen does not move when I move my quadcopter. Sbus on TX1, S.port on RX3,Smart Audio on TX3.

**Comment by jaydeecol** [comment]
Having the same problem with s.port ...I dont use smart audio though

Disabling sport tx3 solves it as a workaround

**Comment by PGIII** [comment]
Resolved in 299
