### ISSUE TITLE
Dead ducked twice on 295

### ISSUE THREAD

**Issue by Rafyel** [RaceFlightOne/RaceFlightOne#131]
Unfortunately, I didn't capture the logs. I'll try to get one.

**Comment by PGIII** [comment]
No one else has reported any issues so sounds like either a failsafe or esc desycnc

**Comment by Fumes74** [comment]
If you mean that it just drops out of the air, yes i have it too. On two builds with 299

**Comment by PGIII** [comment]
We would need a log to see whats happening, if its doing it on flips and rolls then that sounds like an esc desync
