### ISSUE TITLE
PID and Consol history / Timemachine function (Enhancement)

### ISSUE THREAD

**Issue by MHessellund** [RaceFlightOne/RaceFlightOne#132]
A feature to log and track the last (eg.) 10 changes to all PID, filter and Rates setting, including a complete DUMP upon entering Consol, and there after logging all send CLI commands.
This would greatly help when PID tuning and tweaking, as you often need to to know how much the different values was changed. - Today I do this manually as I keep note of alle changes I make when tuning.

A advanced feature would be to be able to rollback change like Mac time machine :)

**Comment by Arti3DPlayer** [comment]
you can export/import all your settings to file(on latests versions), that help you roll back when you needed. Time machine function I guess too complicated for now
