### ISSUE TITLE
Gyro Averaging makes more noise

### ISSUE THREAD

**Issue by cr3pitus** [RaceFlightOne/RaceFlightOne#136]
upon recommendation from @raceflightkid I reduced gyro averaging from 8 to 0 on my yaw axis, and it resulted in less noise on all gyro axes.  Im curious how this could happen and I wonder if the averaging gets skewed from small outliers that end up making them less smooth?

**Comment by rs2k** [comment]
This depends greatly on the rig. On some rigs it helps on some it makes it worse. It's almost always better to have it at 0, but a small amount makes a good compromise between making some quads a little worse and making some quads a little better.
