### ISSUE TITLE
Making FC sound buzzer when battery is low

### ISSUE THREAD

**Issue by FeBoCaMoAl** [RaceFlightOne/RaceFlightOne#140]
Hi. Would it be possible to add to your FCs' firmware a feature to have it sound the buzzer when the battery is low? Since it already gets that info, I would think it could be programmed into the software.

This feature would be great for both FPV pilots using cameras without OSD (like my 2" Millivolt build), and for line of sight.

Thanks! I appreciate your time.

**Comment by PGIII** [comment]
its been in there for a while now, if its not working we can look into but weve had a low voltage alarm since before rc17

**Comment by PGIII** [comment]
already another issue for quiet buzzer, sounds like its working just isn't very loud, we can look into it

**Comment by FeBoCaMoAl** [comment]
Oh, ok. One of your reps said this feature didn't exist. My millivolt is
still on the way.
