### ISSUE TITLE
VFAS is not updating properly, causing intermittent telemetry

### ISSUE THREAD

**Issue by hebster** [RaceFlightOne/RaceFlightOne#142]
Using 299 and earlier, the VFAS telemetry from an XSR (tested both firmware 170605 and 151118) is intermittent, causing "sensor lost" as well as delayed VFAS values sent to X9D plus.

**Comment by mpr52** [comment]
Also experiencing this. On rc17 and 295

**Comment by GiulianoDeMicheli** [comment]
Also experiencing this. On 299. Taranis Plus and XSR EU-LBT on TX1 not updated to the last fw and Tramp HV connected to TX1

**Comment by tjphippen** [comment]
I'm getting this too. Haven't tried yet but heard updating the XSR firmware to the beta version fixed this.

**Comment by papayou66** [comment]
It will not work @tjphippen i tried yesterday to update my xsr

**Comment by GiulianoDeMicheli** [comment]
the problem has come back with RaceFlight One BETA Build 0.320.125. 
My config: Taranis Plus and XSR EU-LBT on TX updated to the last fw, Tramp HV connected to TX4 inverted, revolt v2

**Comment by PGIII** [comment]
should be fixed in 420
