### ISSUE TITLE
Android App CLI

### ISSUE THREAD

**Issue by cr3pitus** [RaceFlightOne/RaceFlightOne#143]
When you go into the apps cli and click in the text box, the keyboard covers what is being typed into the cli.  It would be nice if when you tapped the text box, as the keyboard came up, the cli command prompt also went up so you could make sure you're typing the right thing as you type.  This is on a Google Pixel.  Also, does restoring to defaults in the Android app restore to defaults of the current version correctly?

**Comment by proggod** [comment]
with our pidflight support this should now work
