### ISSUE TITLE
Buzzer it's on during motors spinning

### ISSUE THREAD

**Issue by GiulianoDeMicheli** [RaceFlightOne/RaceFlightOne#146]
Buzzer it's on during motors spinning. I've got buzzer on a switch with arm. Revolt 2 with Taranis Plus and XSR. Fw beta 299. No buzz issue with 238.
Thx for your work :+1:

**Comment by PGIII** [comment]
Do you have the buzzer on the same switch as arm? can you upload a picture of the configuration page with all the modes

**Comment by GiulianoDeMicheli** [comment]
Thank you for the reply. I will upload the image as soon as possible. Yes I've got buzzer on the middle position of the arm switch and arm on the top position.

**Comment by MilanFPV** [comment]
Thats why the buzzer is set up to beep when lipo cell is under 3.8V. Type in console "dump" than it will show you two commands for the buzzer to Turn of or regulate the voltage.

I think 3.8V is not good for stock setting.

_Sent from my Motorola Moto G 2014 LTE using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rs2k** [comment]
Does this problem still exist in 313+?
