### ISSUE TITLE
Current reading through Telemetry and OSD is way off

### ISSUE THREAD

**Issue by techsavvyfpv** [RaceFlightOne/RaceFlightOne#147]
On my quads that have the bolt esc I noticed that the current reading is way off.  Somehow Mah used is correct but current isn't.  When idle telemetry shows current at 30 and when flying I've seen it go over 200.

**Comment by rs2k** [comment]
This has been resolved in 313+

**Comment by MHessellund** [comment]
My current using build 316 is still way off. My used mah is spot on, but current reads up til 600A on my Smartport telemetry.

Issue should be reopened.
