### ISSUE TITLE
GUI needs resize to show Transmitter Setup "NEXT" without scrolling^^

### ISSUE THREAD

**Issue by JulianGoesPro** [RaceFlightOne/RaceFlightOne#148]
GUI needs resize to show Transmitter Setup "NEXT" without scrolling^^

<img width="1440" alt="screen shot 2017-07-02 at 01 26 37" src="https://user-images.githubusercontent.com/11023597/27769800-61ffa7f4-5f32-11e7-8675-c9db236e23cc.png">

Can we just make the pic of the transmitter smaller in favour of showing the "NEXT" button in the lower right corner without the need for scrolling :)

**Comment by Arti3DPlayer** [comment]
this already has been fixed in 0.300
