### ISSUE TITLE
Death SPin/ Infinite Yaw spin 

### ISSUE THREAD

**Issue by RoninMedia12** [RaceFlightOne/RaceFlightOne#149]
On 299 still get Death spin if hit a gate or object!   seems to spin out for about 20-30secs then will correct itself if you are in open space and don't disarm.

**Comment by PGIII** [comment]
We've hit quite a few gates and haven't had any issues, it sounds like you may have an esc going out or a prop is getting stuffed

**Comment by RoninMedia12** [comment]
This has happened on 3 different quads and seems to happen more often on my
lighter builds.  It is strange it will recover some times after spinning
for 30 plus seconds.

**Comment by RoninMedia12** [comment]
I know I have Dvr of at least on instance where this occurred and ended up in the trees as local field had it happened again yesterday and No bent props pulled the quad out of the trees and it flew immediately. No logs I don't think But can try to capture some of when it happens.   I was at a race on Sunday and had to disarm it was witnessed by 30+ people they watched me pick up the quad after and test hover it that was on my 4" build.

**Comment by PGIII** [comment]
its possible the spin stopper may need to kick in sooner for 4in, we use 3in and 5in and dont have any issues, we can make the spin stopper adjustable in the next release so you can adjust it

**Comment by RoninMedia12** [comment]
Thank you thay would be a good thing to be able to adjust for different
builds as my 5 inch does it too but does not seem to be as much. But does
still occur.

On Jul 5, 2017 1:33 PM, "PGIII" <notifications@github.com> wrote:

its possible the spin stopper may need to kick in sooner for 4in, we use
3in and 5in and dont have any issues, we can make the spin stopper
adjustable in the next release so you can adjust it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RaceFlightOne/RaceFlightOne/issues/149#issuecomment-313172884>,
or mute the thread

**Comment by RoninMedia12** [comment]
So can you please explain the ranges for the spin stop in 300.112? and commands   I would like to test it out some today as I have the day off and the weather is nice out.   Thank you

**Comment by PeteG-FPV** [comment]
I've had the yaw spin of death on my quads too (7 different race quads). All 5", running 299. Different ESCs and props.

**Comment by PeteG-FPV** [comment]
I've had the yaw spin of death on my quads too (7 different race quads). All 5", running 299. Different ESCs and props.

**Comment by proggod** [comment]
There is a facebook post on how to adjust this, you can change it in the cli.  We also recommend running reverse prop rotation
