### ISSUE TITLE
Reboot into DFU Fails, Win10 Build 16215

### ISSUE THREAD

**Issue by justingoesfpv** [RaceFlightOne/RaceFlightOne#156]
Device shows and operates fine in FC Mode(Full configuration and everything works without issues)
Device shows and operates fine in BL Mode(Flashing works without issues)
Rebooting from BL mode to DFU Mode results in, "Device Descriptor Request Failed"
Booting into DFU Mode via jumping the PINS operates fine, and flashing firmware is successful.

The issue is only while rebooting via the RF1 GUI from the standard Update mode to DFU mode.

**Comment by hjns** [comment]
You're sure you don't have s.port connected?
