### ISSUE TITLE
RFOSD Voltage Bug (rare)

### ISSUE THREAD

**Issue by JulianGoesPro** [RaceFlightOne/RaceFlightOne#158]
Hey, I noticed my voltage sometimes shows 15 5 instead of (I assume) 15 50, not sure if that is a rounding bug or something, it looks like it is only appearing with 15.50volts, other then that it shows two decimals (which I like) :)

BTW are there going to be "." added so it shows like 16.79 instead of 16 79? (not sure what I like more but just curious ;) )

Thanks!
<img width="1440" alt="screen shot 2017-07-11 at 22 36 14" src="https://user-images.githubusercontent.com/11023597/28089569-c0f64d0e-6689-11e7-8bb3-6148662d5cff.png">

**Comment by apocolipse** [comment]
Same here, it's reporting `15 5` when it's at `15.05`, so needs left padding (and a decimal point)

**Comment by rs2k** [comment]
This will be fixed before release. The current OSD was just a simple implementation to get the important code in place.
