### ISSUE TITLE
TRAMP HV TELEMETRY 

### ISSUE THREAD

**Issue by GiulianoDeMicheli** [RaceFlightOne/RaceFlightOne#161]
Tramp HV telemetry via lua script with Taranis Plus does not work on tx3 or another tx pin. Please solve it. Thx for RC18!

**Comment by spacebubi** [comment]
i've same problem...i've soldered on UARTrx3 the s.port of X4RSB frsky and from TRAMP HV the T wire on the first time at UARTtx3, but i read can give some problems..than i swapped the T wire into another TXuart free on RevoltV2...but...nothing to do. Can resolve it? or better make a detailed guide for all if there a solution? thanks

**Comment by spacebubi** [comment]
there's some specials commnads in console to put ? the smart audio of TBS in tab configuration..is equal to TRAMP HV  "T" wire??? help us please

**Comment by SkeemoFPV** [comment]
It worked on one of the earlier builds (266), but it hasn’t worked since. I know it not my set up as I can flash 266 back on the Revolt v2 and it works, but nothing on any other build.

**Comment by CarbonV** [comment]
I have the same problem, following

**Comment by Quickred** [comment]
Same problem for me.

Lua script on Taranis X9D+ didn't detect TrampHV with 299
connect S.Port from X4R-II to RX3
telemetry works
connect Tramp T on TX4
bridge the pad for TX4 to NOR
in CLI set telem_smartaudio = 0 
in CLI set telem_tramp = 4

no VTX detected :(

with or without NFC connected makes no difference

**Comment by papayou66** [comment]
Same issue on Tx3 or Tx4

**Comment by MilanFPV** [comment]
Same problem here!!

**Comment by hjns** [comment]
I haven't got a tramp to test but it's been reported that like some other variables telem_tramp is zero based instead of one based and that for tx4 it's set telem_tramp=3   A user says this works for him:
![telem_tramp_zero_based](https://user-images.githubusercontent.com/1418353/28943533-24995618-786d-11e7-879b-b28aed9ab75e.png)

Note: this would make it impossible to use tx1 for tramp since 0 is disable.

**Comment by MilanFPV** [comment]
@hjns thats my facebook post, thanks for sharing here. I figured it out with a guy in a german group.

I only tried it on tx4 but maybe it also works on other uarts..

_Sent from my Motorola Moto G 2014 LTE using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MilanFPV** [comment]
Here's the complete post:

------ !!! TRAMP HV DETECTION !!! ------

Today I figured out how to conect the Tramp to change VTX settings on the LUA Script.

Conect the telemetrie of the Tramp to TX4 (jumper normal) and then type this 3 commands in the console:

"set telem_smartaudio=0" - "set telem_tramp=3" - "save"

I dont know why, but only so does it work!!

_Sent from my Motorola Moto G 2014 LTE using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by GiulianoDeMicheli** [comment]
Please advise that it only works with TRAMP V2!

**Comment by rs2k** [comment]
This should be fixed in 313+ 
Please reopen if this issue is not completely resolved.
