### ISSUE TITLE
RF1 GUI fix/enhancment: Motor Noise test

### ISSUE THREAD

**Issue by chargerdude70** [RaceFlightOne/RaceFlightOne#162]
Issue: When doing test, motor 3 and motor 4 results are reversed. 

Is the GUI numbering wrong (meaning motor 3 results are actually motor 4) or is this the intended motor sequence?  If intended, can be confusing to end user. Sequence should match RF1 motor order for consistency.

**Comment by Matthias7Song** [comment]
![img_0794](https://user-images.githubusercontent.com/25809141/28240887-63e68334-69c4-11e7-928e-dab30801e8aa.jpg)

Yes, it's really confusing.

**Comment by Arti3DPlayer** [comment]
Will fixed in next release
