### ISSUE TITLE
GUI doesn't check the range of entries on the PID tab

### ISSUE THREAD

**Issue by hjns** [RaceFlightOne/RaceFlightOne#163]
The gui should limit all entries to the current firmware limits.  For instance the acro plus entries will let you enter over 300 in the gui and then when you reboot the revolt it resets them back to defaults.  This confuses the users and makes them think the settings aren't being saved.  The gui should limit it to 300.    And the same type of thing for all other fields.

The firmware should have a listRanges command that prints all the fields and their low/high/default values.   Then the gui could do that command and check values entered against it.  The defaults value would make it easy for the gui to reset individual fields to default and to highlight ones that have been changed from defaults.

**Comment by Arti3DPlayer** [comment]
@hjns the gui should check, maybe you found the bug)

**Comment by Arti3DPlayer** [comment]
@hjns Will add validation for max min values in next release. Thanks
