### ISSUE TITLE
Renaming Reverse Props to ReversedPropDirection

### ISSUE THREAD

**Issue by JulianGoesPro** [RaceFlightOne/RaceFlightOne#170]
Open for discussion, when I hear "reversed props" I think of mounting them up side down instead of the different rotational direction... 

I am voting for ReversedPropDirection or in this context:
"Do you want to run reversed prop direction?"

...and I just like the acronym RPD 🥇 

Thoughts? :)
<img width="1440" alt="screen shot 2017-07-23 at 15 35 08" src="https://user-images.githubusercontent.com/11023597/28499715-86ddbd6e-6fbc-11e7-99c5-4bc477a22674.png">

**Comment by raceflightkid** [comment]
so we are going to copy betaflight 3.2?

**Comment by proggod** [comment]
You don't think the video is clear? :)
