### ISSUE TITLE
GUI 307 or 306.116 FW issue

### ISSUE THREAD

**Issue by raceflightkid** [RaceFlightOne/RaceFlightOne#172]
RC smoothing when it put to say 33 I get not radio input when it on 1 all his ok

**Comment by Arti3DPlayer** [comment]
@raceflightkid screen please

**Comment by raceflightkid** [comment]
![today](https://user-images.githubusercontent.com/29544554/28540309-d27971dc-70ac-11e7-8934-bdc3b21d98dd.png)

**Comment by raceflightkid** [comment]
i leave it on 1 all is ok , but on 33 no radio inputs i allways use 1 any way

**Comment by Arti3DPlayer** [comment]
@raceflightkid I don't see issue. What did you mean: > no radio inputs  ?

**Comment by raceflightkid** [comment]
well i put rc smoothing on 33  and arm the quad theres no radio inputs , no throttle/yaw/roll/pitch

**Comment by papayou66** [comment]
I just checked i do not have this issue

**Comment by raceflightkid** [comment]
ok im going to close it , it as to me my end
