### ISSUE TITLE
306.116 FW profile bug

### ISSUE THREAD

**Issue by MilanFPV** [RaceFlightOne/RaceFlightOne#173]
On firmware 306.116 the profiles still have bugs.

Also Tramp will not detected in the GUI and rf.lua.

**Comment by PGIII** [comment]
can you be more specific?

**Comment by MilanFPV** [comment]
When I rename the profile1 / profile 2 / profile3 and hit save and than reconect the FC the profiels are no more there. All Rates and and RC Smothing are deleted. Also when the name of the profile is for example "Skitzo Rates" after I reconected the board, the name changed to "SkitzoR"

Sorry for my english, but try to reproduce the problem.

**Comment by Arti3DPlayer** [comment]
@MilanFPV https://github.com/RaceFlightOne/RaceFlightOne/issues/171  is this what you mean?

**Comment by MilanFPV** [comment]
@Arti3DPlayer no that isnt what I mean

_Sent from my Motorola Moto G 2014 LTE using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rs2k** [comment]
Fixed in most recent
