### ISSUE TITLE
310 goes into esc calibration on startup

### ISSUE THREAD

**Issue by cr3pitus** [RaceFlightOne/RaceFlightOne#175]
Upon updating from rc18 to 310, quad immediately goes into esc motor calibration tones after powering on when not connected to configurator.  This occurs with transmitter on, off, or with any other attempt to prevent the issue.  The ESC is a Bolt.  Quad has had no issues and flies all other versions of RF without issue.  If you power on quad while connected to configurator and then unplug quad from PC it operates as normal, but will not power on without calibration tones any other way.

**Comment by rs2k** [comment]
Fixed in most recent
