### ISSUE TITLE
DropDownMenus for Tramp and OSD

### ISSUE THREAD

**Issue by JulianGoesPro** [RaceFlightOne/RaceFlightOne#176]
Just like SmartAudio has it's DropDownMenu could we have one (right next to it) for TrampTLM and RFOSD Tx selection as well? (not hating but rumor has it some don't know that Tramp ain't using SA^^)

Now
<img width="1437" alt="screen shot 2017-08-06 at 19 08 40" src="https://user-images.githubusercontent.com/11023597/29005388-ee7d4862-7ada-11e7-9c34-3e4bd264581c.png">
Suggestion :) (just noticed, the OSD slider could be removed then as well...)
<img width="1437" alt="mockup_screen shot 2017-08-06 at 19 08 40" src="https://user-images.githubusercontent.com/11023597/29005405-5ad527dc-7adb-11e7-9e85-40e79375e683.png">

**Comment by Arti3DPlayer** [comment]
@JulianGoesPro You suggest to change switch widget to dropdown widget ?

**Comment by JulianGoesPro** [comment]
add one for TrampTLM (which corresponds to set telem_tramp=X) and change the switch to dropdown for the OSD (which does not only enable it but lets you select the Tx like the SmartAudio dropdown lets you => set telem_osd=X)

**Comment by hjns** [comment]
Since tramp and SA are never enabled at the same time I'd just add the tramp settings to the current SA dropdown and rename it something like VTX Control.   That would also prevent the problems with people trying to get tramp working with SA turned on.

**Comment by Arti3DPlayer** [comment]
@hjns @JulianGoesPro 
Will add this in next release:
![111](https://user-images.githubusercontent.com/3278913/29088486-dce94f76-7c81-11e7-87be-fdb6b7b9dc91.gif)

**Comment by Arti3DPlayer** [comment]
Added in version 0.314.0

**Comment by JulianGoesPro** [comment]
love it but there is one problem to that, "OTHER" will be both SmartAudio and TrampTLM... some like the Matek-HV will need the TrampTLM protocol, some like *insert one of those here* will need *SmartAudio*... but true, I doubt we will ever need both at the same time :D 

What about OSD dropdown? :(

**Comment by Arti3DPlayer** [comment]
@JulianGoesPro Why you want dropdown for OSD ?:) Why you don't like Switch ?

**Comment by JulianGoesPro** [comment]
easy, for the same reason there is a drop down for the vTx, you can connect the OSD to several USARTs :) Not everyone is using it on Tx4, well, not sure what the default is right now...

**Comment by Arti3DPlayer** [comment]
But what values should be for OSD ?

**Comment by Arti3DPlayer** [comment]
@JulianGoesPro > Matek-HV will need the TrampTLM protocol
oh... show both for other then...

**Comment by JulianGoesPro** [comment]
I would remove "Others" and just rename the two "options" to "SmartAudio" and "TrampTLM"

OSD will work for Tx1 Tx2 Tx3 Tx4 Tx6

**Comment by Arti3DPlayer** [comment]
@JulianGoesPro We need "Others" option in case that in interview user select Other vtx device. That means "SmartAudio" and "TrampTLM" will be disabled. Maybe just rename to "SmartAudio" and "TrampTLM" and leave "Other" ?

**Comment by JulianGoesPro** [comment]
okay, that will do it :)

**Comment by JulianGoesPro** [comment]
Awesome job, love it! One little thing, you can't select Tx6 in the OSD USART selection :)
