### ISSUE TITLE
Configurator Enhancement: Copy Profiles

### ISSUE THREAD

**Issue by denovich** [RaceFlightOne/RaceFlightOne#179]
I want to be able to Copy settings from one profile to another profile. This would allow for faster tuning and setup. Scenario: create baseline tune on Profile 1, copy settings to Profile2 and Profile3. Now make small changes to Profile2 and Profile3, allowing for easy testing of only those changes.

**Comment by Arti3DPlayer** [comment]
duplicate https://github.com/RaceFlightOne/RaceFlightOne/issues/109
