### ISSUE TITLE
Adding RSSI "value" to the OSD

### ISSUE THREAD

**Issue by JulianGoesPro** [RaceFlightOne/RaceFlightOne#180]
I saw the request to get a "number" for RSSI of e.g. a EzHUF in the OSD so those without telemetry can get that info on the OSD (value 0-100 maybe).

The EzHUF just outputs it in vthe PPM or SBus stream as a dedicated channel
The XM and XM+ I think, do the same, right?

To make it easy I think it would be enough (if not implemented right now) to have RSSI in the modes tab and there you can select the channel it is looking for... or is there an easier / more elegant way? :)

**Comment by PGIII** [comment]
added in 420
