### ISSUE TITLE
CPPM + Tramp Not working in 313, causing CPPM to not work

### ISSUE THREAD

**Issue by rdww60** [RaceFlightOne/RaceFlightOne#181]
I've been using 300. Via Slack support configured hardware with EZUHF CPPM on RX3 (CPPM_R3), and Tramp T on TX4, and MinimOSD on TX1 (originally on TX4, but came bad).
With 313, "Radio Setup" does not recognize stick movement using same CPPM_R3 command. With 300, "Radio Setup" does.
I understand Tramp T didn't work until recently, after 300
I found that set telem_tramp=0 using 313 allows "Radio Setup" to recognize stick movement again. Of course no Tramp T use 👎

**Comment by proggod** [comment]
PPM is not fully supported, and since its such an antiquated tech we recommend using betaflight if you need this support.
