### ISSUE TITLE
Unable to use tones in ESC configuration

### ISSUE THREAD

**Issue by yookfpv** [RaceFlightOne/RaceFlightOne#182]
-v 0.300
-Hobbywing ESC 4.1 in multishot mode flashed by Raceflight GUI
-Multishot selected.
imperial march or game of throne tôe selected but still have classic tone on startup.

**Comment by puaka** [comment]
I flash mine with betaflight for the blheli passthrough, then flash my HW 4 in 1 with 16.65 tones. Calibrate the esc in betaflight(multishot). Then reflash raceflight one, no need to recalibrate esc with raceflight, calibration with rf is giving me weird numbers for PPM min and max, betaflight works better on calibration. Once flashed with 16.65, the tones should work on rf esc menu. Good luck!

**Comment by PGIII** [comment]
Thats not going to be calibrated right youre using a lot of power calibrating that way, it should calibrate from 1012 to 1880, around that range, thats correct for race flight. As for it not having the tunes thats likely because we dont have the bin for that esc in there yet we can add it however

**Comment by proggod** [comment]
bin should be supported in 403
