### ISSUE TITLE
Feature Request: GUI Demo mode

### ISSUE THREAD

**Issue by fbertu** [RaceFlightOne/RaceFlightOne#185]
Do you know if there is any way to enter the GUI in demo mode? That is, to be able to look at the new configuration options of the GUI without having to connect the FC?
It would be useful to know and learn to use the GUI, before connecting the FC.
Similar to many flybarless helis rc drive GUI. (Ikon, vbar, etc.)

**Comment by Arti3DPlayer** [comment]
Not sure if this feature will be useful. So I will close this for now
