### ISSUE TITLE
Always Double Arm actually only Single Double Arm anymore

### ISSUE THREAD

**Issue by JulianGoesPro** [RaceFlightOne/RaceFlightOne#186]
When I double arm and fly, disarm, rearm once, I just have to wait a sec and it will arm without doing the real double arm, just like Single Double Arm would do

**Comment by proggod** [comment]
can you try in 402

**Comment by JulianGoesPro** [comment]
I tried 409, still a thing with Spektrum TLM on Tx1, OSD on Tx6 and SmartAudio on Rx3
