### ISSUE TITLE
Setup Tramp HV to 600mw

### ISSUE THREAD

**Issue by GiulianoDeMicheli** [RaceFlightOne/RaceFlightOne#189]
I try to set my Tramp HV from LUA and I can only set a range of power from 25mw to 400mw, I have also an option called unknown. My setup: Revolt V2 fw 0.320 - Tramp HV (connected on inverted TX4) - Taranis plus and xsr updated

**Comment by MilanFPV** [comment]
Same here. There are not the mW steps that the Tramp provides.

**Comment by GiulianoDeMicheli** [comment]
Same with fw 0.343. You cannot use 600mw on Tramp. Why?

**Comment by PGIII** [comment]
duplicate issue, will be fixed with new lua
