### ISSUE TITLE
Invalid throttle values in logs

### ISSUE THREAD

**Issue by Mio44** [RaceFlightOne/RaceFlightOne#190]
Throttle values in logs are messed up, they show values in the millions and billions. Tested on 300 and 324, it was working ok in 317. Rx is frsky xsr.

**Comment by Mio44** [comment]
[flightlog_2017-81-12_93436.txt](https://github.com/RaceFlightOne/RaceFlightOne/files/1297248/flightlog_2017-81-12_93436.txt)
[flightlog_2017-81-12_9408.txt](https://github.com/RaceFlightOne/RaceFlightOne/files/1297258/flightlog_2017-81-12_9408.txt)

**Comment by papayou66** [comment]
I can see this wrong number with betaflight rate log only

**Comment by Mio44** [comment]
I have configured kiss rates.

**Comment by GateslayerFPV** [comment]
I'm having the same thing with ßF rates. BB rates work fine.

**Comment by proggod** [comment]
New logging should fix this
