### ISSUE TITLE
beta340 Aux Channel

### ISSUE THREAD

**Issue by chargerdude70** [RaceFlightOne/RaceFlightOne#195]
Only get 4 channels when detecting RX for Frsky. Used to get 12. Results are I only have 3 AUX channels. Flashed beta340 DFU twice with separate down loads. Flashed back to known good FW and issue went away.

**Comment by PGIII** [comment]
what version gives you all 12 ? it should be limited to 8 so weird if you used to get more

**Comment by chargerdude70** [comment]
Sorry...tile and issue description are misleading. When detecting rx in GUI, the counter tops at 4. It used to go up to 12 just recently and I thought up to 18 in older versions. So its deceiving whether all available channels are getting detected or not.

**Comment by PGIII** [comment]
thats not the amount of channels just the number the protocol is, for instance crossfire is the 22nd protocol it detects, doesnt mean it sees 22 channels
