### ISSUE TITLE
Feature Request - In flight Motor Breaking

### ISSUE THREAD

**Issue by 2mod** [RaceFlightOne/RaceFlightOne#197]
is stopping the motors in flight, on idle throttle, already a planned feature?
only found the parameter to stop them when disarming so far

cheers!

**Comment by PGIII** [comment]
You dont  want the motors to sop in flight unless you want them to disarm, stopping the motors in flight isnt safe and makes them very likely to desync. So motors not spinning at idle is not something we plan on adding

**Comment by 2mod** [comment]
sounds plausible ^^
