### ISSUE TITLE
Quopa mode and Spedix IS30 30A ESC 4-in-1 

### ISSUE THREAD

**Issue by andrewavp** [RaceFlightOne/RaceFlightOne#198]
I have a problem with quopa mode and Spedix IS30 30A ESC 4-in-1 
RF FW 0.343.0 
Quopa mode does not work with a multishot, rotation motors occurs in the same direction.
But when I enable dshot600, everything works fine

**Comment by proggod** [comment]
should be fixed in 403, probably missing a firmware you need for your esc
