### ISSUE TITLE
Configurator very buggy on OSX High Sierra

### ISSUE THREAD

**Issue by denovich** [RaceFlightOne/RaceFlightOne#201]
I had no issues with the configurator for some months... but after updating OSX to High Sierra, I get numerous timeouts and errors saving/loading data. 

Below is what I noticed in the log files...

<img width="1009" alt="screen shot 2017-10-01 at 4 36 53 pm" src="https://user-images.githubusercontent.com/46505/31058757-d64b9d76-a6c6-11e7-913b-0a8a98c601ce.png">

<img width="1163" alt="screen shot 2017-10-01 at 4 30 31 pm" src="https://user-images.githubusercontent.com/46505/31058758-dad44d8e-a6c6-11e7-85ce-c81919f1e768.png">

**Comment by denovich** [comment]
This happened on versions 363, 326

**Comment by Arti3DPlayer** [comment]
@denovich Weird, I have mac os sierra 10.12.6 and it is fine.

**Comment by denovich** [comment]
I had practically zero issues prior to the upgrade to OSX 10.13.  
The problems must be low level... running RF1C in a Windows VM does not work around the issue.

**Comment by denovich** [comment]
Doh!  Seems to be related to one particular Revolt. I tested on my older MBP which is running El Cap.  The first time with a different Revolt... it wasn't until later that I tried the problematic one on the older laptop.

So false alarm.
