### ISSUE TITLE
ImmersionRC Tramp LUA script doesn’t set power levels correctly

### ISSUE THREAD

**Issue by kenkamm** [RaceFlightOne/RaceFlightOne#207]
Taranis LUA script doesn’t work with properly with Tramp VTx. The power level options available don’t match the Tramp options. Max power should be 600 but LUA script says 400. And if you select 400 it puts the Tramp into some unknown power level, had to fix by using buttons on Tramp to set it to 600 mw. Then if I go back into LUA script it reports “unknown power level.”

**Comment by GateslayerFPV** [comment]
I'm getting this as well. I think we might need a LUA update?

**Comment by kenkamm** [comment]
They said they were going to be working on this in the next couple of weeks. I hope they do.

**Comment by PGIII** [comment]
duplicate issue, will be fixed with new lua
