### ISSUE TITLE
Throttle not registering in log - several beta builds

### ISSUE THREAD

**Issue by GateslayerFPV** [RaceFlightOne/RaceFlightOne#208]
With two separate quads I'm getting same issue. When looking at log rcCommand for throttle sticks at 1500 and doesn't move throughout log.

I'm using Taranis radio with R-XSR and X4R-SB receivers on said quads. I'm currently on 261, but have seen this since 320ish.

**Comment by GateslayerFPV** [comment]
I think I might have nailed this down... I believe if you're using ßF rates it doesn't work. If you use BB rates it appears to work.

**Comment by GateslayerFPV** [comment]
Ok this seems to be the same issue as https://github.com/RaceFlightOne/RaceFlightOne/issues/190

**Comment by proggod** [comment]
please test on 402 and update ticket is not fixed
