### ISSUE TITLE
Setup issue with Revolt F4 and RF1

### ISSUE THREAD

**Issue by FPVRaven** [RaceFlightOne/RaceFlightOne#21]
Hi there!
I try 4 bin files now and 3 RF Configurators, but allways if it say "flash sucsessfull" and i replug my usb it will start beeping all 40 seconds and then kick me out of RF Configurator. After about 3 or 4 minutes the beeping stop and then i dont get any response from FC to my computer.
In the window where you can find "RaceFlightOne" you will find "RaceFlightRecovery" at this point and cant connect anymore. I try reinstall all i try replug usb or reopen configurator, nothing fixed it. 
Also i noticed that the blue LED on the FC start flashing if i replug the usb after sucsessfull flash.

My Setup:
- Speed Addict 210R frame 
- Emax RS 2205 2300kv Motors
- DYS XMS 30A ESCs Multishot 14.85/16kHz
- Raceflight Revolt F4 FC
- Catalyst Machineworks PDB with LC Filter (shipped with the Speed Addict frame....)
- Luminer VTX
- Graupner GR12L receiver 
- HS 1177 FPV Camera

**Comment by FPVRaven** [comment]
![0](https://cloud.githubusercontent.com/assets/25104194/21934458/c5527b74-d9a9-11e6-8203-1204eb1ffbd0.png)
![1](https://cloud.githubusercontent.com/assets/25104194/21934459/c55a2a04-d9a9-11e6-97f7-4e125845eba4.png)
![2](https://cloud.githubusercontent.com/assets/25104194/21934460/c55c31c8-d9a9-11e6-8ea2-94a75cdf627a.png)
![3](https://cloud.githubusercontent.com/assets/25104194/21934461/c56651c6-d9a9-11e6-89f1-7ffeeb9936da.png)
![blheli dys](https://cloud.githubusercontent.com/assets/25104194/21934462/c56eaf56-d9a9-11e6-8ac2-a684246fab9a.png)

**Comment by proggod** [comment]
Hopefully this has been fixed for you
