### ISSUE TITLE
FrSky telemetry freezes shortly after takeoff- Beta builds after 320

### ISSUE THREAD

**Issue by kenkamm** [RaceFlightOne/RaceFlightOne#210]
FrSky telemetry doesn’t work reliably. Tested on XSR and R-XSR, both of which running latest FrSky firmware. (Works fine on Betaflight) Telemetry works at first, but after taking to the air the numbers freeze and updates to the Taranis stop. Thus, any voltage or mAh warnings set up in the Taranis don’t work and you end up over-discharging your batteries.

**Comment by djfriesema** [comment]
I am having the same issue, with repeated "Sensor Loss" alerts from the Taranis.

**Comment by 2mod** [comment]
tried the x4r too?

**Comment by djfriesema** [comment]
Is this only an issue with the XSR?  If so I'll get an X4R and try it.

**Comment by 2mod** [comment]
give it a go, the more detail we can get, the easier its for the devs to fix

**Comment by djfriesema** [comment]
One more thing, I'm getting this on 320 which is supposed to be a stable build, so it's not just beta builds where this is occuring.

**Comment by 2mod** [comment]
the most important is the most recent build
ie if it doesnt work on build A but works on B, you could consider it having been fixed (assuming its consistent ofc)
since i doubt there will be separate bug fixing for older builds, as that would exponentially increase the maintenance and risk of further bugs

**Comment by GateslayerFPV** [comment]
I think I'm getting this as well... after arming... you get 16.8v as a readout... when you disarm you get actual voltage.

**Comment by proggod** [comment]
can you guys test on 402

**Comment by proggod** [comment]
reopen if still broken
