### ISSUE TITLE
Spektrum TLM broken in build 374 (quad twitches at idle, eventually failsafes?)

### ISSUE THREAD

**Issue by denovich** [RaceFlightOne/RaceFlightOne#211]
If Spektrum TLM (soldered to TX1) is enabled, upon arm, quad twitches randomly for a few seconds before the motors stop (failsafe?). The quad can be re-armed, but the same behavior happens.

If Spektrum TLM is then disabled via the Configurator, the problem goes away. I can arm and fly as usual.

**Comment by JulianGoesPro** [comment]
that is how it looks for me^^

<img width="1440" alt="screen shot 2017-10-22 at 21 00 55" src="https://user-images.githubusercontent.com/11023597/31865538-454935e4-b770-11e7-98b4-2e81a283b05b.png">

**Comment by RWooten68** [comment]
Some has reported putting the ser on rx3 fixed the issue.

**Comment by JulianGoesPro** [comment]
@RWooten68 will look into that, thanks!

**Comment by RWooten68** [comment]
@JulianGoesPro Don't that wasn't the same issues.

**Comment by JulianGoesPro** [comment]
@RWooten68 well, it makes sense that that exact problem goes away when using Rx3, since it will disable SpekTLM which is the reason for this problem :)

**Comment by denovich** [comment]
I think this is now closed.  TLM seems to work on 419 at least.
