### ISSUE TITLE
"ESC signal smoothing" is not copy when click "copy current profile"

### ISSUE THREAD

**Issue by robomaniac** [RaceFlightOne/RaceFlightOne#212]
Version: 0.320.1
FC Version: 0.320.125 BETA
---------------------------------------
When I am in PID tuning tab and click "_copy current profile values to another profile_" the  "_ESC signal smoothing_" is not copied along.

Mine is enable in profile 1, I then click "_copy current profile values to another profile_" and select profile 2, all the values are copied except the "_ESC signal smoothing_"  that I have to manually enable.

**Comment by Arti3DPlayer** [comment]
@robomaniac sorry, it has been already fixed in 0.374 +
