### ISSUE TITLE
Raceflight Blackbox Viewer 1.2.1 Mac - presets don't save.

### ISSUE THREAD

**Issue by GateslayerFPV** [RaceFlightOne/RaceFlightOne#217]
Don't know if this is a bug or not, but I've noticed that the Raceflight Blackbox Viewer presets don't save after quitting app. This is on version 1.2.1 and on Mac.

**Comment by Arti3DPlayer** [comment]
@GateslayerFPV https://github.com/RaceFlightOne/blackbox-log-viewer/issues/1

Will fix in next release
