### ISSUE TITLE
Crossfire on RX3/TX3 doesn't work anymore (after #324)

### ISSUE THREAD

**Issue by djakette123** [RaceFlightOne/RaceFlightOne#219]
Well crossfire is working fine on RX3 without telemetry.
But when setting telemetry in GUI, radio settings doesn't work anymore and receiver protocol is blank.
Need to disable telemetry and set back radio protocol to CPPM Rx Pin manually.

User should be able to use what uart he wants to setup radio and telemetry.

**Comment by PGIII** [comment]
needs to be set manually, may not auto detect, tx1 is what should be used for the rx, since it doesnt conflict with dshot or logging, telem may have been broken in 324 i would try the latest, 420
