### ISSUE TITLE
Reduce Spacing between top lines so "Radio Data" can be seen without scrolling :)

### ISSUE THREAD

**Issue by JulianGoesPro** [RaceFlightOne/RaceFlightOne#223]
Reduce Spacing between top lines so "Radio Data" can be seen without scrolling :)

<img width="1440" alt="screen shot 2017-11-26 at 14 32 02" src="https://user-images.githubusercontent.com/11023597/33240503-0248ec6e-d2b7-11e7-94bf-6464a83df561.png">

Just shrinking the space between the "lines" would show "Radio Data" that's hidden in the bottom left corner.

Little change but could help prevent frustration for newcomers :)

<img width="1440" alt="screen shot 2017-11-26 at 14 36 21" src="https://user-images.githubusercontent.com/11023597/33240519-3bdcf358-d2b7-11e7-9d10-84643485800c.png">

**Comment by Arti3DPlayer** [comment]
@JulianGoesPro I redid this page in another way already
