### ISSUE TITLE
double arm

### ISSUE THREAD

**Issue by gizmatron** [RaceFlightOne/RaceFlightOne#226]
always double arm STILL doesn't work.. 409 and  double arm after battery is plugged in no problems.. disarm and rearm and its single arm only .. changing arm mode from 1 to 0 either via the configuration page switch OR via console makes no diference. still double then single NOT always double as it should be

**Comment by PGIII** [comment]
ive tested it on frsky, ibus, spektrum, and crossfire and they all double arm all the time, what uart do you have the receiver soldered to

**Comment by gizmatron** [comment]
as in said via email its the smart audio.. turn that off double always comes back.. turn it on and lose it again.. while smart audio is on it works via console to change band/channel/power etc all works

**Comment by kenkamm** [comment]
I also use smart audio and have this problem as well.

**Comment by SkeemoFPV** [comment]
Same here, smart audio and I always get double-single

**Comment by gizmatron** [comment]
I'm glad I'm not the only one.. proggod and preston are working on it apparently. for now I set my channel/band/power in console then turn the smart audio off to fly so i keep the double arm.. haven't tried this with the android app yet but hoping it will work too so i  can change freq at the field without the laptop

**Comment by PGIII** [comment]
do you still have the issue if the vtx is disconnected but smart audio is still enabled ?

**Comment by gizmatron** [comment]
dunno.. not sure I want to unsolder the wire to find out although i suppose its on the edge of the revolt and acesssible.. i'm busy this week so if someone else can test that first ..lol

**Comment by proggod** [comment]
This should be fixed, let us know if not.
