### ISSUE TITLE
Current Consumption and mAh Used wrong on 4.19

### ISSUE THREAD

**Issue by 2dogrc** [RaceFlightOne/RaceFlightOne#228]
Flashed the newest 4.18 and 4.17, current draw and consumed show zero both in the Configurator and on the Radio. Smartport on RX3, Frsky R-XSR, current firmware and RF Bolt.

**Comment by 2dogrc** [comment]
Okay updated to 4.19 AND updated ESC (bolt).  Now I do get current readings, but they are very unstable.  They bounce from 0.3-12 with a constant 5A current set.

**Comment by PGIII** [comment]
should be fixed in 420
