### ISSUE TITLE
Double arm

### ISSUE THREAD

**Issue by RWooten68** [RaceFlightOne/RaceFlightOne#229]
Double Arm is bugged.
If I have Unify's smart audio turn on and connected to RX3 or TX3, it is only making me double-arm once per FC boot, no matter what I have the double-arm setting set on. On first boot you have to double-arm the first time, after that, you can arm the quad as many times as you want by just operation the arm switch once until the FC is booted again. Happens with both Spektrum and FrSky.

If I turn smart audio off, it behaves as it should.

**Comment by gizmatron** [comment]
already opened an issue on this

**Comment by RWooten68** [comment]
Cool

**Comment by PGIII** [comment]
removing because of duplicate
