### ISSUE TITLE
s.port+smartaudio+QUOPA: disable s.port while QUOPA activated.

### ISSUE THREAD

**Issue by fujin** [RaceFlightOne/RaceFlightOne#231]
Follow up to discussion on FB with @PGIII, it may be pragmatic to disable the s.port telemetry output while the FC is switching into QUOPA mode, to avoid the UART3 DMA conflicts (?)

Will test 419 and get steps to reproduce. Placeholder :)

**Comment by PGIII** [comment]
fixed in 420
