### ISSUE TITLE
Configurator GUI: new "switch mode" clicking "off" button to disable mode removes multiple modes

### ISSUE THREAD

**Issue by fujin** [RaceFlightOne/RaceFlightOne#232]
In the newer configuration GUI that detects the switch position, if you set up multiple switches, for example.. brain drain, direct, on AUX6, quopa on AUX8, then "turn off" the Mode by toggling the on/off next to the mode name, it will turn most/all of the other flight modes off as well, causing you to have to set them all up from scratch again.

Steps to reproduce:
- Run wizards
- Add flight modes to auxiliary channels
- Turn off any added flight mode
- Observe multiple flight modes removed/turned off at same time erroneously

**Comment by Arti3DPlayer** [comment]
Will fix in next release(after 0.419.1). Thanks
