### ISSUE TITLE
Taranis telemetry ‘FUEL’ wrong

### ISSUE THREAD

**Issue by SkeemoFPV** [RaceFlightOne/RaceFlightOne#233]
On 419 the mah used reported, is completely wrong. It was previously close, but now getting 35mah reported for a full pack being used.

**Comment by PGIII** [comment]
What does it show when it starts ?

**Comment by 2dogrc** [comment]
Shows 0 on my Taranis on 419, with Bolt.

**Comment by justingoesfpv** [comment]
Should show a % of battery used not total mah consumed, there is a variable for battery size which is currently set to 1300 by default. Doesn't change the fact it's incorrect. But doesn't look like current is correct either for the bolt with the default adc(which is supposed to be for the bolt).

**Comment by 2dogrc** [comment]
Heard there is  beta floating around in the testers section, were you able to fix?

**Comment by PGIII** [comment]
Should be fixed in 420, reopen this issue if the problem still persists,  checked with my bolt and it now seems to be pretty close, it is setup to use percent for fuel
