### ISSUE TITLE
Changing profiles on PID page does not load new values if current Profile has been edited

### ISSUE THREAD

**Issue by denovich** [RaceFlightOne/RaceFlightOne#234]
As seen on version 418:
Steps to reproduce:
Make change to Profile 1
Use dropdown to switch to profile 2

Notice how values are still from Profile 1?

**Comment by Arti3DPlayer** [comment]
@denovich Well, all three profiles are same after first install. So make some changes and you will see difference. Also, notice that some variables are same for all profiles.
