### ISSUE TITLE
Minimum filter level is 30, but dynamic ultralow preset is 25, changes to 45 on save

### ISSUE THREAD

**Issue by denovich** [RaceFlightOne/RaceFlightOne#235]
as seen on 418 and 419.2

steps to reproduce:

select Dynamic filter
change Roll, Pitch or Yaw Filter Level to a value less than 30
save 
change tabs
go back to pids tab and look at Filter level, it will have changed to 45.

**Comment by PGIII** [comment]
will be fixed in next version, ultr low will also be changed to be 30
