### ISSUE TITLE
Level mode issue

### ISSUE THREAD

**Issue by shawreid05** [RaceFlightOne/RaceFlightOne#239]
In level mode when quad touches ground to land quad jumps up and does a flip and lands upside down

**Comment by PGIII** [comment]
we can look into it, what version are you using ? and does it always do this ?

**Comment by shawreid05** [comment]
I am currently running 419, yes always does this amazing flip in level mode
soon as it touches the ground. does not do this in accro.

thanks
Shawn reid

**Comment by PGIII** [comment]
does acrolevel have the same issue ? We can try to see if we can replicate it

**Comment by shawreid05** [comment]
Yes acro level same thing

Shawn reid

**Comment by PGIII** [comment]
Cant get it to do the same thing for me, have you tried the latest version it could be something like an esc desyncing

**Comment by shawreid05** [comment]
It’s 419. I will try to put 421 on tomorrow and see if it’s still there. 

Shawn reid

**Comment by PGIII** [comment]
im closing this issues since we havent had any issues with level mode in the latest versions, if your problem persists feel free to pm us on FB or slack and we can help you figure it out
