### ISSUE TITLE
Use Channel 16 for RSSI on Frsky XM+ and XM Receivers

### ISSUE THREAD

**Issue by 2dogrc** [RaceFlightOne/RaceFlightOne#242]
The XM+ does not have telemetry, but it does output RSSI on Channel 16.  Can we enable that as some kind of selection in the config.  Here is a video from Project Blue Falcon.
https://www.youtube.com/watch?v=q-rOd4_DSIk

**Comment by PGIII** [comment]
should be easy enough to do i can look into it

**Comment by PGIII** [comment]
should work in the latest it was added for frsky, currently works on channel 8 or 16 for frsky
