### ISSUE TITLE
FW420RC2: Configurator Telemetry Pane behaves erroneously

### ISSUE THREAD

**Issue by fujin** [RaceFlightOne/RaceFlightOne#245]
After upgrading to FW420RC2 I noticed that the Telemetry pane behaves strangely:

Steps to reproduce:
* Upgrade FC FW to 420RC2
* Run through Wizard 1 to configure accelerometer (quad on flat surface, quad on nose)
* Switch to telemetry panel
* Rolling to right rolls the 3d model to the right
* Rolling to left rolls the 3d model to the right
* Pitching forward pitches the 3d model backward until it reaches 90deg, then it resets sharply
* Pitching backward pitches the 3d model backward until it reaches 90deg, then it resets sharply
* Yaws semi-constantly

Expected:
* Telemetry panel works normally after Wizard 1

Workaround:
* None known. Potentially ignore-able. May also be causing issues with Level mode or QUOPA's FC position detection.

**Comment by PGIII** [comment]
Its likely because the acc needs to be recalibrated after the oreintation is set when you unplug and plug back in does it work normally ?

**Comment by fujin** [comment]
@PGIII Still same behavior after re-plug.

**Comment by SkeemoFPV** [comment]
Seeing the same issue here.

**Comment by PGIII** [comment]
fixed in 500
