### ISSUE TITLE
Smartaudio support for TBS Unify using Radio (Spek/Taranis)

### ISSUE THREAD

**Issue by magnazan** [RaceFlightOne/RaceFlightOne#25]
Please add the ability to change settings using the radio for the TBS Unify via smartaudio

**Comment by rs2k** [comment]
Partial support added. Work in progress.

**Comment by deepimpactio** [comment]
How can I test this feature @rs2k?

**Comment by rs2k** [comment]
This feature has been added. It will be in the next release. :)
