### ISSUE TITLE
LED board doesn’t work on skitzo fc

### ISSUE THREAD

**Issue by DragonCloudzero** [RaceFlightOne/RaceFlightOne#250]
I have wired up a diatone flash-bang sw402 with 8 2812 leds on the board. I have tried flashing the firmware with three different firmwares and the led board will only display white light. I can’t get the led board into any of the modes or change the color. I tried different 5v locations and made no difference. Please help. Thank you

**Comment by PGIII** [comment]
Sounds like the leds may not be addressable, leds have been tested in the latest versions and do work, how do you have it wired ?

**Comment by PGIII** [comment]
leds tested and working on latest, if you have any questions or need help setting them up feel free to ask on FB or slack
