### ISSUE TITLE
Arming while switching profiles.

### ISSUE THREAD

**Issue by se1v3rt** [RaceFlightOne/RaceFlightOne#253]
Found a bug maybe. when changing from profile 1 to profile 2, I armed the quad before it got done switching/rebooting whatever it does. It flipped the F out when I finally armed it all the way... lol (edited)
disarmed rearmed and the motors made some strange sounding idle noise. Flipped out on any throttle. Had to unplug and replug to get it back normal. Never thought to force this kind of error before... Just got in a hurry trying to beat darkness...

Also, might want to put a pause on switching profiles. I notice that if you go from 1 to 3 or 3 to 1, it seems to switch twice just from listing to the tones. making sure the switch stays on said profile for more than 300 - 400 ms should be long enough to stop the double switching and short enough to not be noticeable to the end user. Assuming it is actually switching to 2 then 3 when going from 1 to 3.

I also have double arm on.

**Comment by proggod** [comment]
this should be fixed
