### ISSUE TITLE
Can't update esc

### ISSUE THREAD

**Issue by federik21** [RaceFlightOne/RaceFlightOne#254]
Hi guys, total newbie to RF here. I have a revolt v2, but I can't get to finish the ESC update wizard page. It's keeping saying to connect the battery, but the battery is connected, and my esc are doing the arming tone. If I do the motor calibration, I can calibrate the esc (my escs are dys aria 35a).
Version: 0.426.2
FC Version: 0.420.144 BETA
FC Hardware: RaceFlight Revolt

**Comment by PGIII** [comment]
blheli32 escs cant be updated, you need to use the blhlei32 configurator to update them
