### ISSUE TITLE
TBS VTx Will Not Transmit When Armed if Battery is Plugged In On Profiles 2 or 3

### ISSUE THREAD

**Issue by 8BBB** [RaceFlightOne/RaceFlightOne#256]
Question: V500.147/Spark/Millivolt/TBS Race setup on two Big Deal 3" and one 5" Twig. All fly excellent and do everything well....except one odd thing. In order to turn the TBS video Tx on, they must be in Profile 1 when plugged in. After turning the VTx on, then they may be switched to Profile 2 or 3 and the VTx remains on. If the board is in Profile 2 or 3 when plugged in, the VTx will not allow it to be turned to on and transmit. This is the same on all three quads. No a big deal but I cannot find why this occurs. Any thoughts?  Also, this is with Taranis X7S/RXSR setup.  When running the RF LUA telemetry script, it must be on Profile 1 to recognize the VTx.  Thanks, Bob

**Comment by PGIII** [comment]
we could check, do you have it set to go into pit mode on startup ?

**Comment by 8BBB** [comment]
Correct.  The Unify is in Pit Mode and begins transmitting normally VTXON with the same switch as the ARM switch.  Profile One must be selected during power up or it will not exit Pit Mode.

**Comment by proggod** [comment]
This should be fixed, let me know if it is not.

**Comment by 8BBB** [comment]
It works correctly in all three profiles now.  Thank you.
________________________________
