### ISSUE TITLE
A more Postive locking connector on Bolt and Revolt cable

### ISSUE THREAD

**Issue by LuckyFPV** [RaceFlightOne/RaceFlightOne#258]
I believe a recent midair reboot was the cause of the connector slightly backing out of the esc. I feel a postive locking mechanism would be a big plus on both the bolt and revolt.  I'm adding a dab of hot glue and have not seen the problem since

**Comment by proggod** [comment]
I think hot glue is an excellent way to keep them connected, since its easy to pop off.  We can look into changing connectors in the future, but so far this has been the best one we can easily put on the fc and esc.
