### ISSUE TITLE
"mah" shows up in OSD as current in amps

### ISSUE THREAD

**Issue by jake09mid** [RaceFlightOne/RaceFlightOne#261]
"mAh" is correct in the RaceflightOne configuration page. However, choosing to display "mah" on the internal OSD of the RevoltOSD board actually shows current in amps on the OSD. A correct mAh on the OSD will help pilots land at the appropriate battery capacity rather than rely on the jumpy voltage reading of the OSD.

**Comment by PGIII** [comment]
fixed in 572
