### ISSUE TITLE
GUI problem on 4K screen

### ISSUE THREAD

**Issue by mpkiteman** [RaceFlightOne/RaceFlightOne#30]
On  4K  screen, impossible to set up quad.
In setup quadcopter, the red button right low corner is invisible.
![rf1 4k](https://cloud.githubusercontent.com/assets/25844276/23065117/2dc64e58-f514-11e6-8dbc-9a95db680298.jpg)

Impossible to resize window to reach it.
Even with task bar hidden, or left or right, this button is invisible.

**Comment by Arti3DPlayer** [comment]
fixed in newest versions

**Comment by mpkiteman** [comment]
Perfect. Thanks
