### ISSUE TITLE
S Port Telemetry VFAS - Missing

### ISSUE THREAD

**Issue by rigo3t** [RaceFlightOne/RaceFlightOne#32]
Telemetry for FrSky is now working for me, but I don't get VFAS, I get only accelerometer readings and other Rx provided readings like RSSI and SWR and RxBt.

This would be the most useful thing in Telemtry, Vbat is connected on my board.

**Comment by digitalomni** [comment]
what build version are you on? 185 or 189?

**Comment by Enri636** [comment]
also in 190 and 191 dont work yet

**Comment by rs2k** [comment]
191 should be working now. Please make sure telemetry is enabled "set telem_sport=14" and the s.port pin is connected to the USART RX pin 3 and there is voltage going to the VBAT pin on the revolt.

**Comment by Enri636** [comment]
i did , but i m on V1 fc , i meen pdf wire diagram for sport , are different for V1 and V2

**Comment by DebPack** [comment]
Hi the wiring diagram for Revolt V1 is wrong, you need to wire to RX3 to get telemetry.
Also VFAS working in 191

**Comment by rigo3t** [comment]
On my Revolt 2 it's working also. But I didn't know the wiring was wrong in the Revolt 1. I have both boards in different quads. I will try to rewire my Revolt 1 tomorrow morning and come back with results.

**Comment by Enri636** [comment]
yes work :)

**Comment by proggod** [comment]
Great then i am going to close out this issue, just make sure you use RX3 on v1 or v2, we have now noted this in configurator
