### ISSUE TITLE
Dectect receiver don't work on 190 FW/GUi

### ISSUE THREAD

**Issue by Spirre** [RaceFlightOne/RaceFlightOne#33]
Just installed 190 FW and 190 GUI on a Mac and I can't get detect receiver to work, it times out and the FC reboots and a message comes up afterwards that says the "rx wizard timeout"

Worked just fine on 185 just before this

**Comment by Spirre** [comment]
Tried again on my Windows PC and there it works

**Comment by rs2k** [comment]
Fixed in 191.
