### ISSUE TITLE
ESC Tab

### ISSUE THREAD

**Issue by Driftfc7** [RaceFlightOne/RaceFlightOne#35]
Save function is esc tab does not save any settings for any of the categories. This is with The latest Config posted for Firmware version 193.

**Comment by Driftfc7** [comment]
Also, using 1wire through cli does not save settings. It says it changed them and then after saving and redoing a 1wire read, the settings are still unchanged.

**Comment by rs2k** [comment]
What ESC was this on?

**Comment by PGIII** [comment]
esc tab works and saves settings in latest version
