### ISSUE TITLE
Can't use TX4 with Logging on

### ISSUE THREAD

**Issue by adefliesfpv** [RaceFlightOne/RaceFlightOne#36]
TX4 cannot be used for a receiver when logging is enabled. Motors will arm and turn off immediately, then won't re-arm. When setting logging to a switch, quad will arm and fly normal with switch in off position but as soon as logging switch is turned on, motors will turn off.

**Comment by PGIII** [comment]
will be fixed in the future, for now use tx1

**Comment by adefliesfpv** [comment]
haha, responding to my ticket.

**Comment by PGIII** [comment]
logging disabled when using tx4
