### ISSUE TITLE
Motors going full rpm after power off radio

### ISSUE THREAD

**Issue by Shinjo01x** [RaceFlightOne/RaceFlightOne#37]
...even if disarmed before.

guys, this is dangerous!

**Comment by proggod** [comment]
Need more information like which kind of radio how your fail safe is set up what version your using etc

**Comment by Shinjo01x** [comment]
Radio is Taranis x9d plus. Fail safe ist set up to a Switch, disarm is set to a Switch. 

If I disarm, than power off the Radio, after 10 sec delay Motors going sull rpm for about 10 sec. 
If I disarm, than fail safe, than power off, nothing happens. 

But even if fail safe is working, this is kinda dangerous. Luckily i ll notices this with probs off. I can reproduce this every time.

**Comment by Shinjo01x** [comment]
RF Version: 0.168.049_alpha_revolt_full

**Comment by proggod** [comment]
Yes this bug has been fixed, always make sure your using latest when reporting bugs, give it a try in latest version.
