### ISSUE TITLE
Blackbox log - when using Kiss Rates the rc commands are wrong

### ISSUE THREAD

**Issue by Therotak** [RaceFlightOne/RaceFlightOne#43]
When using Kiss rates it happends that the rc commands in the logs are totally wrong. The go up to 20k 

![rcomm](https://cloud.githubusercontent.com/assets/24692072/23372184/e4539276-fd1a-11e6-8b56-df6705e95ca4.JPG)

**Comment by rs2k** [comment]
This should be fixed in 199+ (RC3+)
