### ISSUE TITLE
Buzzer Past RF1 191

### ISSUE THREAD

**Issue by LexRotor** [RaceFlightOne/RaceFlightOne#45]
Since RF1 191, the buzzer emits a small beep until I disarm the quad.
If I put buzzer on a switch, it's work's great.

**Comment by rs2k** [comment]
Is it a distinct beep or a constant tone?

**Comment by LexRotor** [comment]
It's a distinct beep and less strong than the strat

**Comment by rs2k** [comment]
This is working correctly in the latest dev builds.
