### ISSUE TITLE
Set motor order in gui

### ISSUE THREAD

**Issue by dane-if3** [RaceFlightOne/RaceFlightOne#49]
If your FC is rotated (or you have soldered the motors in an odd order) it would be nice to be able to fix this or at least see this in the gui. (obviously the idle n commands are how to check)
When you do the board calibration it knows the board is different. Perhaps the motor direction and idle wiz could spin one motor at a time and ask if it is on the correct corner as well as the correct direction.
With buttons Correct, wrong motor, wrong direction, cancel

**Comment by rs2k** [comment]
This feature is planned and will be added after release 1.0. :)

**Comment by proggod** [comment]
Duplicate issue
