### ISSUE TITLE
Feature request: Ability to control/test each motor in GUI.

### ISSUE THREAD

**Issue by r1b4z01d** [RaceFlightOne/RaceFlightOne#51]
I would love to be able to make sure my ESC wiring is correct by powering on a single motor at a time.

**Comment by Deckoz2302** [comment]
Currently you can do this in CLI
idle 0
Idle_stop

**Comment by rs2k** [comment]
@Arti3DPlayer Let's add a testing section to the configuration page. One for the motor test and one for the idle testing.

**Comment by Arti3DPlayer** [comment]
added
