### ISSUE TITLE
PID page save

### ISSUE THREAD

**Issue by JVBAV8** [RaceFlightOne/RaceFlightOne#54]
please address PID Tuning page.
issues seen are rates values disappear, and will not save.
PID values also will not save
WIN 32 version and Windows 10

**Comment by JVBAV8** [comment]
when save button is clicked, no dialog box appears confirming values were saved.
CLI dump confirms no changed values are saved.
changing values in CLI does work, but GUI PID Tuning page is unusable.

**Comment by Arti3DPlayer** [comment]
Do you have 32-bit windows system ?

**Comment by JVBAV8** [comment]
Yes. Win32. Tried Win64 GUI, but it won't run on my system

**Comment by Arti3DPlayer** [comment]
on 32-bit is known issue, but what about 64 ? did you download 64-bit program version? and what happened ?

**Comment by JVBAV8** [comment]
I downloaded it, but it won't run on my system. I tried to run it

**Comment by MHessellund** [comment]
Ive seen it on 64bit version: Some times the PID/filter values doesnt load (ie. all or some of the fields are left blank, and other might load fine). I can enter values in alle field (incl. the blank ones). But when I push save, it will not save.
I can switch to another pane, and back to PID's, and every think will load fine.

**Comment by rs2k** [comment]
This has been fixed in the 199+. There will be an RC3 soon. :)

**Comment by JVBAV8** [comment]
Thank you. Awesome!
Releasing 199 soon?
What is RC3?
Sorry to have more questions
