### ISSUE TITLE
Add auto map esc to nearest corner on board orientation wizard

### ISSUE THREAD

**Issue by magnazan** [RaceFlightOne/RaceFlightOne#55]
Could you please add the option to the existing Board Orientation wizard which auto maps the nearest corner to the ESC so regardless of orientation you always solder to the nearest corner of the revolt.

**Comment by JulianGoesPro** [comment]
love the idea... just may upset those already wired it like normal... hm... still think it's a good idea (came here to post it lol)

**Comment by rs2k** [comment]
This has been added in the latest configurator.
