### ISSUE TITLE
Add support for IRC Tamp HV Serial connection

### ISSUE THREAD

**Issue by MHessellund** [RaceFlightOne/RaceFlightOne#58]
Please expand the comming SmartAudio feature to include IRC Tramp HV serial interface for vtx configuration.

**Comment by proggod** [comment]
We may need to get some tramp hardware to add that

**Comment by MHessellund** [comment]
Ok. I'll poke around and see what I can do...

**Comment by rs2k** [comment]
With some hardware to test and the protocol documentation it won't take long to get this added.

**Comment by MHessellund** [comment]
I do belive that your now in contact with IRC? (or so I hear) :)
Hope you get what you need.

**Comment by rs2k** [comment]
Added to most recent versions
