### ISSUE TITLE
Flight Controller Setup Failure - Step 2

### ISSUE THREAD

**Issue by lawlessfpv** [RaceFlightOne/RaceFlightOne#60]
I have a STIGG build I am working on and have installed the Skitzo FC. Trying to go through the Flight controller setup wizard and I get stuck on STEP 2. I get an error...Calibration Failed.  The board does have to be rotated on the YAW Axis 31 degrees in the frame. So this may or may not have an affect on STEP 2 when the wizard asks you to flip the quad on its nose and hit next
![20170310_115358](https://cloud.githubusercontent.com/assets/26417836/23918834/8755443a-08c2-11e7-92aa-b31d42b3b7b4.jpg)
.  Thank you in advance for your help.
![the_st1gg_1024x1024](https://cloud.githubusercontent.com/assets/26417836/23918837/8ad04632-08c2-11e7-8301-5c3afefe0f9d.jpg)
![image](https://cloud.githubusercontent.com/assets/26417836/23919034/407d9084-08c3-11e7-8843-f669c8205d0a.png)

**Comment by rs2k** [comment]
This feature has been added in 199+ (RC3)

Skip the first FC calibration wizard and do this in console:
set gyro_rotation=0
set board_calibrated=1
set sml_board_rot_x=0
set sml_board_rot_y=0
set sml_board_rot_z=31 (or -31 for left)
save

**Comment by lawlessfpv** [comment]
Did this and went through RX Detection and Radio Setup.  But now I get this error...
![image](https://cloud.githubusercontent.com/assets/26417836/24002619/398b9de4-0a2f-11e7-91e8-bb026d9415f4.png)

**Comment by lawlessfpv** [comment]
Console Command complete, but now I get all kinds of errors about RC Command timeout, RC1 command timeout, dump command errors....thoughts?
![image](https://cloud.githubusercontent.com/assets/26417836/24003046/58d5d222-0a30-11e7-89b0-c714207c3bbc.png)
![image](https://cloud.githubusercontent.com/assets/26417836/24003050/5cb5c672-0a30-11e7-8dbc-0821bf876b45.png)

**Comment by Arti3DPlayer** [comment]
@lawlessfpv i guess problem in you receiver or maybe board was out of sync. Did you try to reconnect/connect and do wizard again ?

**Comment by Arti3DPlayer** [comment]
No details provided
