### ISSUE TITLE
5.3ghz aka L-band support for Unify / Tramp

### ISSUE THREAD

**Issue by denovich** [RaceFlightOne/RaceFlightOne#62]
The Unify and Tramp, by SmartAudio and/or wand, also support transmitting on channels in the 5.3ghz band. These channel defs would need to be added in order to select them.

**Comment by Deckoz2302** [comment]
I would suggest implementing custom frequencies similar to the core pro, which allows you to set your frequency down the the 1mhz.  Basically any channel between 5300 and 6000.

**Comment by rs2k** [comment]
closing duplicate
