### ISSUE TITLE
Buzzer beep from contiunesly to periodic (enhancement - low priority)

### ISSUE THREAD

**Issue by MHessellund** [RaceFlightOne/RaceFlightOne#65]
When activating the buzzer, you have a continues sound. This continues sound is harder to locate when using it to locate a lost model. 
It would be preferable to have a beep --- beep --- beep sound, so the sound can be easier located.

Perhaps a CLI command to switch between continius and periodic beep’ing.

**Comment by PGIII** [comment]
Fixed in latest version
