### ISSUE TITLE
Implement CRSF protocol

### ISSUE THREAD

**Issue by Deckoz2302** [RaceFlightOne/RaceFlightOne#68]
Crossfire now supports a bidirectional serial protocol CRSF V2. Protocol is 150hz, must use non inverted pad on FC.

Reasons for request:
-telemetry on smartport and spektrum has been done already
-telemetry on crossfire is needed
-telemetry provides a way to view/change PID and Smart Audio

Please contact Trappy or TBS freshdesk if more info is needed.

**Comment by storm13** [comment]
Would love to see this implemented - ready and willing to test.

**Comment by Enri636** [comment]
me too looking for that :)

**Comment by Enri636** [comment]
no news good news or whtttttt :)

**Comment by PGIII** [comment]
working since 324
