### ISSUE TITLE
Quad will freak out sometimes after liftoff but power cycling will fix it

### ISSUE THREAD

**Issue by JulianGoesPro** [RaceFlightOne/RaceFlightOne#73]
Preston says it's me not having the Arm switch in the right position... well thinking about it... I think I might have had the Tx on the wrong model since it's happening mostly on the "first time flying it"... so yeah... might be really connected to the Rx data^^

**Comment by rs2k** [comment]
This has been resolved. Please let me know if it is not @JulianGoesPro. :)
