### ISSUE TITLE
Spektrum TLM (vBat) not working in .215 on my DX8

### ISSUE THREAD

**Issue by JulianGoesPro** [RaceFlightOne/RaceFlightOne#76]
SPM4649T on Tx3 Revolt V1 and G1 DX8 DSMX 11ms

**Comment by JunkAK** [comment]
Same experience. All worked well in Rc7 but only getting 0.0volts in Rc8.

**Comment by PGIII** [comment]
working in RC12, make sure to add voltage to the telemtry screen in the radio
