### ISSUE TITLE
Please support Reaktor OSD/PDB

### ISSUE THREAD

**Issue by knifeproz** [RaceFlightOne/RaceFlightOne#77]
Hey there, id like to ask for support for reaktor pdb/osd board which is a plate replacement for the alien pdb. I believe it's running mwosd, so I know this may have already been requested but please support it on the reaktor! :)

**Comment by JulianGoesPro** [comment]
what current sensor is on it?

**Comment by knifeproz** [comment]
The specifications are here: https://droneplastics.com/Attachments/Reaktor_PDB_OSD_Install_Rev2.pdf
However I believe it said 0-5v under current sensor so 5v?

**Comment by rs2k** [comment]
This should work in the next RC (Should be RC16) Please try it out when its ready. :)
