### ISSUE TITLE
Please support MWOSD style osd 

### ISSUE THREAD

**Issue by DoubleAfpv** [RaceFlightOne/RaceFlightOne#78]
I use the follow osd below which requires a connection to the FC via serial/UART port to get telemetry etc. 
http://www.diatoneusa.com/store/p234/Diatone-SP3-40ch-VTX-0_25_200_600mw-Pigtail

Awesome work - great product so far,  thanks guys

**Comment by rs2k** [comment]
This has been added as of build 233. :)
