### ISSUE TITLE
Support for FC & VTx Configuration with TBS Vision OSD / VTx

### ISSUE THREAD

**Issue by Mauronic** [RaceFlightOne/RaceFlightOne#79]
Every time you have to use one button and a 1mm LED to configure a VTx a kitten dies.

 ![image](https://cloud.githubusercontent.com/assets/6380582/24393043/700180e4-134b-11e7-89a5-475acb9671f2.png)

http://www.team-blacksheep.com/products/prod:FPVision

Snip from marketing copy

> FULL GRAPHICS OSD
> Don't worry about sacrificing functionality for weight. With a full-graphics OSD, the possibilities are endless. Nice analog "fuel" gauges, different size text and fonts, clean and readable menus! The POWERCUBE FPVision lets you use RC Stick commands (BST or Colibri FC required) to customize all aspects of your on-screen display, as well as tune your flight control (Colibri FC required).

**Comment by rs2k** [comment]
OSD functionality is being implemented now.
