### ISSUE TITLE
configurator:  captures escape even when it's not the top window

### ISSUE THREAD

**Issue by hjns** [RaceFlightOne/RaceFlightOne#80]
On linux if the configurator is running it captures escape even when another program is the top window.  This prevents the use of any program that depends on using the escape key unless you quit the configurator.   Not checked on other platforms.   0.208.062 version.

**Comment by hjns** [comment]
it's reported that this occurs on the Mac too.

**Comment by Arti3DPlayer** [comment]
will fix in next release
