### ISSUE TITLE
USB Error

### ISSUE THREAD

**Issue by nksmith4747** [RaceFlightOne/RaceFlightOne#84]
When connecting the FC to the GUI on Windows 10 it will not connect and times out.  Various releases were tried 195, 222.  None worked.  It was possible to update the firmware on the FC but not connect.  The same FC would connect when using a PC running Ubuntu.  I then tried connecting to the Windows PC using a different USB port and it connects fine using all releases.  The difference between the two USB ports is that the USB port that does not work is USB 3, while the USB that does work is USB 2,1.

**Comment by PGIII** [comment]
That sounds like that maybe more of a software or hardware issue with the computer it's self, I'd check for windows updates, but if the USB 2 ports work and it works fine on Linux that sounds like it could be windows or the computer it's self causing issues
