### ISSUE TITLE
Enable acces to CLI commands through s.port and Lua script (enhancement)

### ISSUE THREAD

**Issue by MHessellund** [RaceFlightOne/RaceFlightOne#86]
Open up so that is is possible to send CLI commands through a Opentx lua script and FrSky s.port, and receive a response.
This would open up for 3.part lua scripts to configure RF1 on the fly using Opentx.

**Comment by rs2k** [comment]
We will be looking to expand the scripting after Release 1.0 is out.

**Comment by MHessellund** [comment]
Cool, it'll open up for som cool community expansions! - Keep up the good developing ;)
