### ISSUE TITLE
 RaceFlight One Client Build 0.226.00: VTX PITMODE TYPE commands are backwards. 

### ISSUE THREAD

**Issue by TomT4S** [RaceFlightOne/RaceFlightOne#88]
VTX On after power cycle, puts it in Pitmode after power cycle.

VTX Pitmode after power cycle, turns it on after power cycle.

**Comment by GateslayerFPV** [comment]
So which one is right? the release notes or the gui?

**Comment by rs2k** [comment]
Resolved in latest dev builds
