### ISSUE TITLE
CLI commands have no effect on vTx channel (SmartAudio)

### ISSUE THREAD

**Issue by JulianGoesPro** [RaceFlightOne/RaceFlightOne#90]
Example... 

`#ms Unknown Command:...sending "vtxinfo"
#me vtx.vtxDevice=2
#me vtx.vtxBand=4
#me vtx.vtxChannel=5
#me vtx.vtxBandChannel=37
#me vtx.vtxPower=1
#me vtx.vtxPit=0
#me vtx.vtxRegion=0
#me vtx.vtxFrequency=5843
#ms Unknown Command:....sending "vtxbandchannel r1"
#me vtx.vtxDevice=2
#me vtx.vtxBand=4
#me vtx.vtxChannel=0
#me vtx.vtxBandChannel=32
#me vtx.vtxPower=1
#me vtx.vtxPit=0
#me vtx.vtxRegion=0
#me vtx.vtxFrequency=5658
#ms Unknown Command:...sending "vtxinfo"
#me vtx.vtxDevice=2
#me vtx.vtxBand=4
#me vtx.vtxChannel=5
#me vtx.vtxBandChannel=37
#me vtx.vtxPower=1
#me vtx.vtxPit=0
#me vtx.vtxRegion=0
#me vtx.vtxFrequency=5843`

the vTx seems to respond with the "suggested" channel but checking if it actually moved (vtxinfo) shows it didn't... looking at my goggles band scanner... same story... vtx isn't changing channel at all :(

(working with both Taranis lua skript and Spektrum TLM (at least allowed channels))

**Comment by GateslayerFPV** [comment]
I couldn't even get VTXON and VTXPIT to work. VTXINFO worked fine.

**Comment by rs2k** [comment]
fixed in recent buids
