### ISSUE TITLE
Feature Request: Add low raceband frequencies for TBS Unify Race

### ISSUE THREAD

**Issue by hjns** [RaceFlightOne/RaceFlightOne#91]
Request from slack user:

Add low raceband frequencies for TBS Unify Race to the telemetry script.

**Comment by cturn** [comment]
I second this request :dancer:

**Comment by rs2k** [comment]
What are the low race band frequencies?

**Comment by cturn** [comment]
Low Band Frequencies are:
5325mhz
5348mhz
5366mhz
5384mhz
5402mhz
5420mhz
5438mhz
5456mhz

**Comment by hjns** [comment]
I'm wondering if there are multiple ones, I found this on the web;

![tbs_unify_pro_race_quickstart](https://cloud.githubusercontent.com/assets/1418353/25260079/cb18376e-2617-11e7-90c3-3240ce51ff72.jpg)

**Comment by cturn** [comment]
I think they're are, was wondering that as I was typing the list as they didn't sound right.  But, the ones you listed are obviously the correct unify L-band channels, thanks!

**Comment by rs2k** [comment]
Planned for release 1.0

**Comment by PGIII** [comment]
added in latest
