### ISSUE TITLE
Power Mode setting not active with LUA enabled with Unify

### ISSUE THREAD

**Issue by stucarius** [RaceFlightOne/RaceFlightOne#97]
I have noticed that when I turn on my V2 5V Unify that the amber light and board setting options are not available. The settings are there in the LUA Script on the Taranis and the VTX is operating but there is no indicator. There is also no visual indicator or setting prompt for Pitmode and Racemode. No matter what the VTX seems to only boot into Racemode. My install of the pre-RC17 created no issues with this although there is no way of moving from Pit to Race modes in the OSD Script. Is this going to be added to the Script and that is why the function seems to be gone?

**Comment by rs2k** [comment]
Resolved now. :)
